# Project: Student Performance Dashboard

In [1]:
import numpy as np
import pandas as pd

In [2]:
StudentInfo={
    "Name":["Neelraj","Ruturaj","Prashant","Harsh","Tushar","Shyam"],
    "Marks":[67,84,92,78,95,58],
    "Attendance":[95,88,72,81,98,65]
}

In [3]:
df=pd.DataFrame(StudentInfo)

**Display Complete Student Data**

In [4]:
df

       Name  Marks  Attendance
0   Neelraj     67          95
1   Ruturaj     84          88
2  Prashant     92          72
3     Harsh     78          81
4    Tushar     95          98
5     Shyam     58          65

In [5]:
df.head()

       Name  Marks  Attendance
0   Neelraj     67          95
1   Ruturaj     84          88
2  Prashant     92          72
3     Harsh     78          81
4    Tushar     95          98

**Statistical Analysis**

In [6]:
print("MARKS ANALYSIS")
print("Average Marks:",df["Marks"].mean())
print("Highest Marks:",df["Marks"].max())
print("Lowest Marks:",df["Marks"].min())

print("\n")

print("ATTENDANCE ANALYSIS")
print("Average Attendance:",df["Attendance"].mean(), "%")
print("Highest Attendance:",df["Attendance"].max(),"%")
print("Lowest Attendance:",df["Attendance"].min(),"%")

MARKS ANALYSIS
Average Marks: 79.0
Highest Marks: 95
Lowest Marks: 58


ATTENDANCE ANALYSIS
Average Attendance: 83.16666666666667 %
Highest Attendance: 98 %
Lowest Attendance: 65 %

**Topper's Identification**

In [7]:
topper=df["Marks"].idxmax()
print("Topper of the class:")

print(f"Topper:{df.loc[topper,'Name']} ({df.loc[topper,'Marks']}marks)")

Topper of the class:
Topper:Tushar (95marks)

**Highest & Lowest Marks**

In [8]:
highest_attendance=df["Attendance"].idxmax()
lowest_attendance=df["Attendance"].idxmin()

print("\nAttendance Analysis")

print(f"Highest Attendance : {df.loc[highest_attendance,'Name']} ({df.loc[highest_attendance,'Attendance']}%)")
print(f"Lowest Attendance : {df.loc[lowest_attendance,'Name']} ({df.loc[lowest_attendance,'Attendance']}%)")

Attendance Analysis
Highest Attendance : Tushar (98%)
Lowest Attendance : Shyam (65%)

**Student Scoring Above 80**

In [9]:
print("\nStudent Scoring Above 80")
score=df[df["Marks"]>80]
print(score)

Student Scoring Above 80
       Name  Marks  Attendance
1   Ruturaj     84          88
2  Prashant     92          72
4    Tushar     95          98

**Low Attendance Warning**

In [10]:
print("\nLow Attendance Alert")

low_attendance=df[df["Attendance"]<75]
print(low_attendance)

Low Attendance Alert
       Name  Marks  Attendance
2  Prashant     92          72
5     Shyam     58          65

**Grade Assignment**

In [11]:
def calculate_grade(marks):
    if marks>=90:
        return "A"
    elif marks>=80:
        return "B"
    elif marks>=70:
        return "C"
    elif marks>=60:
        return "D"
    elif marks>=50:
        return "E"
    else:
        return "F"

df["Grade"]=df["Marks"].apply(calculate_grade)
print(df)

       Name  Marks  Attendance Grade
0   Neelraj     67          95     D
1   Ruturaj     84          88     B
2  Prashant     92          72     A
3     Harsh     78          81     C
4    Tushar     95          98     A
5     Shyam     58          65     E

**Grade Distribution**

In [12]:
print("\nGrade distribution")
print(df["Grade"].value_counts())

Grade distribution
Grade
A    2
D    1
B    1
C    1
E    1
Name: count, dtype: int64

**Sort Student by Marks**

In [13]:
print("\nStudents Sorted by Marks")
sorted_df=df.sort_values(by="Marks", ascending=False)
print(sorted_df)

Students Sorted by Marks
       Name  Marks  Attendance Grade
4    Tushar     95          98     A
2  Prashant     92          72     A
1   Ruturaj     84          88     B
3     Harsh     78          81     C
0   Neelraj     67          95     D
5     Shyam     58          65     E

**Top 3 students**

In [15]:
print("\nTop 3 students")
top_3=df.sort_values(by="Marks", ascending=False).head(3)
print(top_3)

Top 3 students
       Name  Marks  Attendance Grade
4    Tushar     95          98     A
2  Prashant     92          72     A
1   Ruturaj     84          88     B

**Bottom 3 Students**

In [16]:
print("\nBottom 3 students")
bottom_3=df.sort_values(by="Marks").head(3)
print(bottom_3)

Bottom 3 students
      Name  Marks  Attendance Grade
5    Shyam     58          65     E
0  Neelraj     67          95     D
3    Harsh     78          81     C

**Pass Percentage**

In [17]:
print("Pass Percentage")
passed_students=len(df[df["Marks"]>=40])
total_students=len(df)

pass_percentage=(passed_students/total_students)*100
print(f"\nPassing Percentage is: {pass_percentage:2f} %")

Pass Percentage

Passing Percentage is: 100.000000 %